services:
  backend:
    container_name: online_marketplace
    image: online_marketplace
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=online_marketplace
      - DB_CONTAINER=db
      - DB_PORT=3306
      - DB_USERNAME=user1
      - DB_USER_PASSWORD=pass
      - DB_ROOT_PASSWORD=root_pass
    networks:
      - market_net
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: 'mysql:8.0.0'
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 20s
      interval: 4s
      retries: 5
    environment:
      - MYSQL_DATABASE=online_marketplace
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - market_net
    expose:
      - 3306


volumes:
  db_data:
networks:
  market_net: