spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_marketplace
    username: market_user
    password: market_password
    root_password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  database:
    name: online_marketplace

logging:
  level:
    org.springframework: DEBUG